name: Docker Build Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add Maven Github authentication
        run: |
          mkdir -p ~/.m2
          echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd'> <servers> <server> <id>github-crypt4gh</id> <username>${{ github.GH_USER_FOR_MAVEN_ACTIONS }}</username> <password>${{ secrets.GH_PAT_FOR_MAVEN_ACTIONS }}</password> </server> <server> <id>github-clearinghouse</id> <username>${{ github.GH_USER_FOR_MAVEN_ACTIONS }}</username> <password>${{ secrets.GH_PAT_FOR_MAVEN_ACTIONS }}</password> </server> </servers> </settings>" > ~/.m2/settings.xml

      - name: Build Docker image
        run: docker build -t sda-doa:test .
